### ISSUE TITLE
Reusing Factorio Mod code in https://wiki.nixos.org

### ISSUE THREAD

**Issue by SigmaSquadron** [nicball/nuc-nixos-configuration#1]
Hi there! I was recently overhauling some pages in the official NixOS wiki, and I stumbled upon your code on the [Factorio page](https://wiki.nixos.org/wiki/Factorio#Mods). As your configuration does not have a license, we're not sure if we can distribute it under the MIT license the Wiki uses.

As your code is very useful for anyone modding Factorio, would you consider licensing the Factorio file under the MIT or a similar copyfree license?

Thank you!

**Comment by nicball** [comment]
Glad to help. I have added an MIT license.
Also factorio.nix has been improved a bit. Now you don't have to copy the whole mod dir when you change a single mod zip.

**Comment by SigmaSquadron** [comment]
Thank you! Your code is now up at https://wiki.nixos.org/wiki/Factorio#Mods.
